import React from 'react'
import Navbar from '../Components/Navbar'
import Footer from '../Components/Footer'
import { Typography } from 'antd'
import ConnectWithUs from '../Components/ConnectWithUs';
import Menu from '../Components/Menu';

const {Title} = Typography;
function DisclaimerPage() {
  return (
    <>
      <Navbar/>
      <Menu/>
          <div className="matrimony">
            <div className="sattojanamAbout">
                <Title level={2} className="titleStyle">Disclaimers</Title>
                <p>sattonjanam.com is not responsible for any incorrect or inaccurate Content/listing posted on the Site or in connection with the sattonjanam.com Service, whether caused by Users, Members or by any of the equipment or programming associated with or utilized in the Service, nor for the conduct of any User and/or Member of the sattonjanam.com Service whether online or offline.</p>
                <p>sattonjanam.com is not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any web site or combination thereof, including injury or damage to Users and/or Members or to any other person's computer related to or resulting and/or in connection with the sattonjanam.com Service.</p>
                <p>Under no circumstances will sattonjanam.com be responsible for any loss or damage resulting from anyone's use of the Site or the Service and/or any Content posted on the sattonjanam.com Site or transmitted to sattonjanam.com Members. You should not provide your financial information (for example, your credit card or bank account information), or wire or otherwise send money, to other Members.</p>
                <p>The exchange of matchmaking profile(s) through or by "sattonjanam.com" is not a matrimonial offer and/or recommendation from/by sattonjanam.com. sattonjanam.com shall not be responsible for any loss or damage to any individual arising out of, or subsequent to, any relations (including but not limited to matrimonial relations) established pursuant to the use of sattonjanam.com.</p>
                <p>sattonjanam.com does not assume any responsibility or liability for any illegal Content posted on the Site by any Members, users or any third party.</p>
                <p>All liability, whether civil or criminal arising out of any Content that is Posted on the Site will be of that Member / user / third party who has Posted such Content and sattonjanam.com reserves its right to claim damages from such Member/ user / third party that it may suffer as a result of such Content Posted on the Site. sattonjanam.com does not claim ownership of Content you submit or make available for inclusion on the Service.</p>

                <Title level={2} className="titleStyle">Other</Title>
                <p>By becoming a Member of the sattonjanam.com service, you agree to receive certain specific email from sattonjanam.com. You can unsubscribe at any time for any reason quickly and easily by clicking on the unsubscribe link enclosed in the mail. You can also manage your subscription by modifying the privacy settings.</p>
                <p>This Agreement, accepted upon use of the Site and further affirmed by becoming a Member of the sattonjanam.com service, contains the entire agreement between you and sattonjanam.com regarding the use of the Site and/or the Service. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect.</p>
                <p>If you have any questions about this Terms of Use, the practices of this site, or your dealings with this Web site, please email us or contact us at info@sattonjanam.com</p>
                <p>By becoming a member of sattonjanam.com and/or using the Services of the Site, you unconditionally and irrevocably confirm that you have read and understood the above terms and agree to abide by them during your membership with sattonjanam.com.</p>
                <p>If you are not agreeing to any of the above terms and conditions, please refrain yourself from registering on the Site.</p>
                <p>Please contact us with any questions regarding this service agreement by writing to info@sattonjanam.com.</p>
                <p>This Agreement is an electronic document in terms of the Information Technology Act, 2000 and Rules thereunder pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            </div>
          </div>
          <ConnectWithUs/>
      <Footer/>
    </>
  )
}

export default DisclaimerPage
